name: Node.js CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]  # Test across different Node.js versions

    steps:
    - uses: actions/checkout@v4  # Checkout the repository code
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'  # Cache Yarn dependencies
    - name: Install dependencies
      run: yarn install
      working-directory: ./server  # Set the working directory to 'server'
    - name: Run tests
      run: yarn test
      working-directory: ./server  # Set the working directory to 'server'
